### PR TITLE
Fix v1.2.0

### PR DESCRIPTION
**Pull request by Claymm**
This fixes the regex of **v1.2 of blade-extension** for Laravel 4.2.* in order to allow whitespaces in instructions like "@foreach (...)" for example.
**This shouldn't be merged with develop branch but with v1.2.0 tag.**

### CODE REVIEW

**Comment by Claymm** [comment]
You might want to have a look to the regex for v2.0 as well actually.

**Comment by RobinRadic** [comment]
Good one. Thanks!

I will integrate the changes into the develop branch and release it with 2.1. Following that i will release a patched 1.2.1 as well. 

This will take a few more days as i am aiming towards better code quality, testing, documentation and more (optional) functionality.

**Comment by Claymm** [comment]
Hey! Did you fix v1.2 with this?

**Comment by RobinRadic** [comment]
Oh, forgot about that. Will make sure to implement it soon

**Comment by RobinRadic** [comment]
v1.2.1 tagged which fixes this

**Comment by Claymm** [comment]
THANKS!

**Comment by Claymm** [comment]
Just realized that 
``@foreach ($array as $key => $value)`` (with a space between foreach and the parenthesis)
wasn't defining the $loop variable.
Any idea why?

**Pull request closed without merging**
