### PR TITLE
@ifsection directive

### PR DESCRIPTION
**Pull request by unstoppablecarl**
Added `@ifsection` directive related to [#39]

### CODE REVIEW

**Comment by RobinRadic** [comment]
After seeing this pull request, i checked the `Illuminate\View\Factory` code and noticed this method for all the laravel `> 5.0` versions. This should indeed be included by the `SectionsTrait`. 

Since for some reason i failed to notice this, i'll be going over all the code again and see if there's anything else that needs attention.

About the blade directive `@ifsection` . I'm not that eager to add it. I'll have some thoughts about it when i have the time next weekend. I'll get back on that topic by then.

Thanks a lot :+1:

**Comment by unstoppablecarl** [comment]
In my haste to submit the pull request, I forgot to post the explanation to go with it. :sweat_smile:

`@ifsection` allows patterns like this:

**panel.blade.php**
```
<div class="panel">

    @ifsection('header')
    <div class="panel-header">
        @yield('header')
    </div>
    @endifsection

    <div class="panel-content">
        @yield('content')
    </div>

    @ifsection('footer')
    <div class="panel-footer">
        @yield('footer')
    </div>
    @endifsection

</div>
```

**example-without-footer.blade.php**
```
@extends('panel')

@section('header')
    This is the header
@endsection

@section('content')
    This is some content
@endsection
```

**example-without-header.blade.php**
```
@extends('panel')

@section('content')
    This is some content
@endsection

@section('footer')
    This is the footer
@endsection
```

It becomes much more useful when combined with `@embed`

**page.blade.php**
```
@embed('panel')
    @section('header')
        This is the header
    @endsection

    @section('content')
        This is some content
    @endsection
@endembed
```

I agree `@ifsection` is probably not the ideal solution to this specific problem. A helper function would be much better as it could be used as a param within other directives. I was unable to figure out how to make one that accomplished the same thing. Do you have any alternative ideas for implementing this pattern? or how it could be done with a helper function?

**Comment by RobinRadic** [comment]
My reluctance to add the directive is mostly because i don't want the package to include an X amount of directives that:
- the majority will never use
- can cause conflicts with existing directives for peoples application

The `@minify` and `@markdown` directives for example. But i can't remove them now anymore.

I have been considering a 'Optional directives' kind of thing. Where you need to specifically enable those optional directives in the configuration file. By doing so it's no problem to add even a 100 more directives, no matter how usefull or useless they are.

**Comment by unstoppablecarl** [comment]
Sounds like it is time to work on a new point release.

Is there something about `@ifsection` you think will cause conflicts with other directives?

Do you have any alternative ideas for implementing this pattern? or how it could be done with a helper function?

**Comment by RobinRadic** [comment]
Similair to the `@foreach` its `$loop` variable, i could expose something like a `$embed` variable, giving you access to the `EmbedStack`. Also its possible then to implement `ArrayAccess` on it and maby some `__get` `__set` magic to get stuff out of the 'EmbedStack->vars` property. At least you would be able to do something like:

```php
<div class="panel">

    @if($embed->hasSection('header'))
    <div class="panel-header">
        @yield('header')
    </div>
    @endif

</div>
```

**Comment by unstoppablecarl** [comment]
That seems like an ok solution. There are some problems with injecting variables though. Collision etc. It is also harder to read.

Is there a way to define global functions only for view rendering?

**Comment by RobinRadic** [comment]
Not sure, il get back on that once i checked up on that.
Right now the `$embed` actually already exists, as `$__env`.

I'd say it should be rather easy for any developer to create a `@ifsection` directive that replaces with `<?php if($__env->hasSection('header'): ?>`

At this moment, i'm mostly in favour of adding it as 'optional directive' as mentioned previously.

**Comment by RobinRadic** [comment]
@unstoppablecarl added as optional directive since `7.0.2` [config/blade-extensions.php](https://github.com/RobinRadic/blade-extensions/blob/7.0.2/config/blade-extensions.php)

**Pull request closed without merging**
